import type { Metadata } from "next";
import "./globals.css";
import Aside from "@/components/castom/Aside";
import {
	NavigationMenu,
	NavigationMenuContent,
	NavigationMenuIndicator,
	NavigationMenuItem,
	NavigationMenuLink,
	NavigationMenuList,
	NavigationMenuTrigger,
	NavigationMenuViewport,
} from "@/components/ui/navigation-menu"
import { IoMdAdd } from "react-icons/io";

export const metadata: Metadata = {
	title: "Home . Threads",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased flex items-center justify-between w-full `}
			>
				<Aside />
				<div className="w-[500px]">
					<center className="py-1 flex items-center justify-center text-white">
					Для вас
						<NavigationMenu>
							<NavigationMenuList>
								<NavigationMenuItem> 
									<NavigationMenuTrigger className="bg-black text-[#dadcde] hover:bg-black cursor-pointer"></NavigationMenuTrigger>
									<NavigationMenuContent className="bg-[#181818] text-white border-none">
										<NavigationMenuLink className="cursor-pointer">Link</NavigationMenuLink>
										<NavigationMenuLink className="cursor-pointer">Link</NavigationMenuLink>
									</NavigationMenuContent>
								</NavigationMenuItem>
							</NavigationMenuList>
						</NavigationMenu>
					</center>
					<main className="max-w-[500px] w-full mx-auto bg-[#181818] h-[92vh] rounded-2xl overflow-y-auto">
						{children}
					</main>
				</div>
				<button className="text-white"><IoMdAdd size={25} className="bg-[#171717] w-25 h-20 m-4 rounded-lg hover:w-27 hover:h-22 transform" /></button>
			</body>
		</html>
	);
}
