import type { Metadata } from "next";
import { TbBrandThreads } from "react-icons/tb";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";

export const metadata: Metadata = {
	title: "Home . Threads",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`antialiased flex items-center justify-between w-full `}
			>
				<aside className="flex flex-col justify-between h-screen w-fit px-4 py-6">
					<Link href="/">
						<TbBrandThreads color="white" size={34} />
					</Link>
					<nav>
						<ul className="flex flex-col gap-4 text-[#6B6B6B] ">
							<li>
								<Link href="/">
									home
									{/* <Image
										src="/navigation/home.svg"
										alt="icon"
										width="20"
										height="20"
									/> */}
								</Link>
							</li>
							<li>
								<Link href="/search">
									search
									{/* <Image
										src="/navigation/search.svg"
										alt="icon"
										width="20"
										height="20"
									/> */}
								</Link>
							</li>
							<li>add</li>
							<li>
								<Link href="/activity">
									activity
									{/* <Image
										src="/navigation/like.svg"
										alt="icon"
										width="20"
										height="20"
									/> */}
								</Link>
							</li>
							<li>
								<Link href="/profile">
									profile
									{/* <Image
										src="navigation/profile.svg"
										style={{ fill: "#6B6B6B" }}
										alt="icon"
										width="20"
										height="20"
									/> */}
								</Link>
							</li>
						</ul>
					</nav>
					<div>
						<button>pin</button>
						<button>set</button>
					</div>
				</aside>
				<main className="max-w-[500px] w-full mx-auto bg-white h-[95vh] rounded-2xl overflow-y-auto">
					{children}
				</main>
				<button className="text-white">+</button>
			</body>
		</html>
	);
}
